/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Instructor, InstructorCreate } from './dtos/Instructor.dto';
import { InstructorController } from './Instructor.controller';
import { InstructorService } from './Instructor.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('InstructorController', () => {
  let controller: InstructorController;
  let spyService: InstructorService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: InstructorService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [InstructorController],
      providers: [InstructorService, ApiServiceProvider],
    }).compile();

    controller = module.get<InstructorController>(InstructorController);
    spyService = module.get<InstructorService>(InstructorService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call InstructorController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call InstructorController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Instructor();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
