/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Instructor } from './Instructor.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { InstructorService } from './Instructor.service';
import { InstructorController } from './Instructor.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Instructor])],
  providers: [InstructorService],
  exports: [InstructorService],
  controllers: [InstructorController],
})
export class InstructorModule {}
