/**
 * This file generated by Apso.
 */
import { CourseModule } from './Course/Course.module';
import { StudentModule } from './Student/Student.module';
import { AssignmentModule } from './Assignment/Assignment.module';
import { InstructorModule } from './Instructor/Instructor.module';

export default [
  CourseModule,
  StudentModule,
  AssignmentModule,
  InstructorModule,
];
