/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Student } from './Student.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { StudentService } from './Student.service';
import { StudentController } from './Student.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Student])],
  providers: [StudentService],
  exports: [StudentService],
  controllers: [StudentController],
})
export class StudentModule {}
