import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class StudentCreate {
  @ApiProperty()
  first_name: string;
  @ApiProperty()
  last_name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  enrollment_date: string;
  @ApiProperty()
  status: string;
}

export class Student {
  @ApiProperty()
  id: number;
  @ApiProperty()
  first_name: string;
  @ApiProperty()
  last_name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  enrollment_date: string;
  @ApiProperty()
  status: string;
}
