/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Course, CourseCreate } from './dtos/Course.dto';
import { CourseController } from './Course.controller';
import { CourseService } from './Course.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('CourseController', () => {
  let controller: CourseController;
  let spyService: CourseService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: CourseService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [CourseController],
      providers: [CourseService, ApiServiceProvider],
    }).compile();

    controller = module.get<CourseController>(CourseController);
    spyService = module.get<CourseService>(CourseService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call CourseController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call CourseController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Course();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
