/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Course } from './Course.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CourseService } from './Course.service';
import { CourseController } from './Course.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Course])],
  providers: [CourseService],
  exports: [CourseService],
  controllers: [CourseController],
})
export class CourseModule {}
